@startuml
<style>
' TODO: Export to a generic style sheet
componentDiagram {
    LineColor darkblue
    TextColor blue

    agent {
        BackGroundColor palegreen
    }
    .Virtual {
        BackGroundColor lightgray
    }
    database {
        BackGroundColor white
    }
    actor {
        LineColor black
    }
}
document {
  BackGroundColor white
}
</style>

actor "Command Line Interface" as cli
actor "Calls to application" as ext_call

node Cluster as cluster <<Virtual>> {
    node "Kubernetes Controller(s)" as controller <<Concrete>> {
        agent "API Server" as c_api_gw
        agent "Scheduler" as c_scheduler
        agent "Controller Manager" as c_mngr
        database "etcd" as c_etcd

        c_api_gw --> c_scheduler
        c_api_gw --> c_mngr

    }

    node "Node 1" as kube_worker_1 <<Virtual Machine>> {
        agent "Kubelet" as kubelet_1
        agent "Kube-Proxy" as proxy_1
        agent "Container Runtime" as docker_1

        cloud "Pod A" as pod_A_1 <<Virtual>> {
            agent "Application container" as container_A_1
        }

        kubelet_1 --> docker_1
        docker_1 ..> pod_A_1

        container_A_1 <-- proxy_1
    }

    node "Node N" as kube_worker_2 <<Virtual Machine>> {
        agent "Kubelet" as kubelet_2
        agent "Kube-Proxy" as proxy_2
        agent "Container Runtime" as docker_2

        cloud "Pod A" as pod_A_2 <<Virtual>> {
            agent "Application container" as container_A_2
        }
        cloud "Pod B" as pod_B_2 <<Virtual>> {
            agent "Application container" as container_B_2
        }

        kubelet_2 --> docker_2
        docker_2 ..> pod_A_2
        docker_2 ..> pod_B_2

        container_A_2 <-- proxy_2
        container_B_2 <-- proxy_2
    }

    cloud "Service A" as service_a <<Virtual>> {
    }

    cloud "Service B" as service_b <<Virtual>> {
    }

    cloud "Ingress" as ingress <<Virtual>> {
    }

    proxy_1 <-- service_a
    proxy_2 <-- service_a
    proxy_2 <-- service_b

    service_a <-- ingress
    service_b <-- ingress
}


cli --> c_api_gw
ingress <-- ext_call

c_api_gw ---> kubelet_1
c_api_gw ---> kubelet_2
@enduml