@startuml
<style>
' TODO: Export to a generic style sheet
componentDiagram {
    LineColor darkblue
    TextColor blue

    agent {
        BackGroundColor palegreen
    }
    cloud {
'        BackGroundColor lightgray
        BackGroundColor white
    }
    database {
        BackGroundColor white
    }
    node {
        BackGroundColor white
    }
    actor {
        LineColor black
    }
}
document {
  BackGroundColor white
}
</style>

actor "Calls to application" as ext_call

node Cluster as cluster {
    node "Default" as ns <<Namespace>> #lightgrey {
        node "Node 1" as kube_worker_1 <<Virtual Machine>>  #white {
            agent "Kube-Proxy" as proxy_1

            cloud "my-web-server-1" as pod_A_1 <<Pod>> {
                agent "Nginx" as container_A_1
            }
            container_A_1 <-- proxy_1
        }

        node "Node 2" as kube_worker_2 <<Virtual Machine>> #white {
            agent "Kube-Proxy" as proxy_2

            cloud "my-web-server-2" as pod_A_2 <<Pod>> {
                agent "Nginx" as container_A_2
            }
            cloud "my-web-server-3" as pod_B_2 <<Pod>> {
                agent "Nginx" as container_B_2
            }

            container_A_2 <-- proxy_2
            container_B_2 <-- proxy_2
        }

        cloud "simple-web-service-clusterip" as service_a <<Service>> {
        }

        cloud "simple-web-ingress" as ingress <<Ingress>> {
        }

        cloud "simple-web-config" as configmap <<ConfigMap>> {
        }
        cloud "simple-web-secrets" as secret <<Secret>> {
        }

        cloud "simple-web-ingress" as ingress <<Ingress>> {
        }

        proxy_1 <-- service_a
        proxy_2 <-- service_a

        service_a <-- ingress

        ' Formatting
        configmap -[hidden]- secret
    }

    note as about_node
        The Nodes can be used by any other namespace
        at the same time.
    end note
    about_node ..> kube_worker_1
    about_node ..> kube_worker_2
}


ingress <-- ext_call
@enduml