@startuml
<style>
' TODO: Export to a generic style sheet
componentDiagram {
    LineColor darkblue
    TextColor blue

    agent {
        BackGroundColor palegreen
    }
    cloud {
'        BackGroundColor lightgray
        BackGroundColor white
    }
    database {
        BackGroundColor white
    }
    node {
        BackGroundColor white
    }
    actor {
        LineColor black
    }
}
document {
  BackGroundColor white
}
</style>

' Force diagram as Component
node Cluster as cluster
node Cluster as cluster {
    node "Node 1" as kube_worker_1 <<Virtual Machine>> {
    }
    node "Node 2" as kube_worker_2 <<Virtual Machine>> {
    }

    node "StorageClass" as storage_class
    node "PersistentVolume" as volume

    node "Default" as ns <<Namespace>> #lightgrey {
        node "Pod 1" as pod_A_1 <<Pod>> {
        }
        node "Pod 2" as pod_A_2 <<Pod>> {
        }
        node "Pod 3" as pod_B_2 <<Pod>> {
        }
    }

    node "Another" as ns2 <<Namespace>> #lightgrey {
        node "Pod 4" as pod_B_1 <<Pod>> {
        }
        node "Pod 5" as pod_C_1 <<Pod>> {
        }
        node "PersistentVolumeClaim" as volume_claim

        pod_C_1 --> volume_claim: Uses
    }

    kube_worker_1 ..> pod_A_1: Hosted by
    kube_worker_1 ..> pod_B_1: Hosted by
    kube_worker_1 ..> pod_C_1: Hosted by

    kube_worker_2 ..> pod_A_2: Hosted by
    kube_worker_2 ..> pod_B_2: Hosted by

'    volume ..> volume_claim
    volume_claim <.. volume: Bind
    volume <.. storage_class: Creates
}
@enduml