@startuml
<style>
' TODO: Export to a generic style sheet
componentDiagram {
    LineColor darkblue
    TextColor blue
    BackGroundColor white

    agent {
        BackGroundColor palegreen
    }
    .Virtual {
        BackGroundColor lightgray
    }
    database {
        BackGroundColor white
    }
    actor {
        LineColor black
    }
    arrow {
        LineColor black
    }
}
document {
  BackGroundColor white
}
</style>

node "CSV Connector" as source <<Source>>
node "MongoDB Connector" as sink <<Sink>>

node "Kafka Cluster" as cluster #lightgrey {
}

database "MongoDB" as db
database "CSV File" as file_sink

file_sink <. source

source -> cluster

cluster -> sink
sink -> db


@enduml